name: Flaky Test Check

on:
  push:
    branches:
      - main

jobs:
  flaky-test-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    # clone the test's repo
    - name: Clone Repo
      run: |
        cd ~
        git clone https://github.com/vojtechhabarta/typescript-generator
        cd typescript-generator
      
      # print the latest commit
    - name: Print Commit Hash
      run: |
        cd ~/typescript-generator
        git rev-parse HEAD

    - name: Install Maven
      run: sudo apt-get update && sudo apt-get install -y maven

    - name: Compile Module
      run: mvn clean install -DskipTests -pl typescript-generator-core -am

    - name: Run Test
      run: mvn -pl typescript-generator-core test -Dtest=cz.habarta.typescript.generator.TaggedUnionsTest#testTaggedUnionsWithInterfaces

    - name: Run NonDex
      run: mvn -pl typescript-generator-core edu.illinois:nondex-maven-plugin:2.1.1:nondex -Dtest=cz.habarta.typescript.generator.TaggedUnionsTest#testTaggedUnionsWithInterfaces
